name: Bump Version and Publish

on:
  push:
    branches:
      - main
    paths:
      - src/**/*

jobs:
  bump-and-publish:
    name: Bump Version and Publish to NPM
    if: "! contains(toJSON(github.event.pull_request.labels.*.name), 'release-skip')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          registry-url: "https://registry.npmjs.org"
          cache: 'npm'

      - name: Clean Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Determine version bump type
        id: version_type
        run: |
          if echo "${{ toJSON(github.event.pull_request.labels.*.name) }}" | grep -q 'release-minor'; then
            echo "version_type=minor" >> $GITHUB_ENV
          else
            echo "version_type=patch" >> $GITHUB_ENV
          fi

      - name: Bump version
        run: npm version ${{ env.version_type }} --no-git-tag-version

      - name: Publish NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          PACKAGE_VERSION=$(jq -r .version package.json)
          git add package.json package-lock.json
          git commit -m "chore: bump up package version to $PACKAGE_VERSION"
          git push origin main        
