name: Bump Patch Version and Publish

on:
  push:
    branches:
      - main
    paths:
      - src/**/*

jobs:
  check-label:
    name: Check for Skip Label
    runs-on: ubuntu-latest
    outputs:
      has_skip_label: ${{ contains(github.event.pull_request.labels.*.name, 'skip-release') }}

  bump-and-publish:
    name: Bump Patch Version and Publish to NPM
    if: needs.check-label.outputs.has_skip_label == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump patch version
        run: npm version patch --no-git-tag-version

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          npm --no-git-tag-version version patch
          PACKAGE_VERSION=$(jq -r .version package.json)
          
          git add package.json package-lock.json
          git commit -m "chore: bump up package version to $PACKAGE_VERSION"
          git push origin main

      - name: Build project
        run: npm run build

      - name: Publish dist to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
